"""empty message

Revision ID: fd4564879a76
Revises:
Create Date: 2022-10-25 15:45:25.597977

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd4564879a76"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_magic",
        sa.Column("character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("current_mp", sa.Integer(), nullable=True),
        sa.Column("total_mp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core.character.id"],
            name=op.f("fk_character_magic_character_id_character"),
        ),
        sa.PrimaryKeyConstraint("character_id", name=op.f("pk_character_magic")),
        schema="plugin_magic",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_magic", schema="plugin_magic")
    # ### end Alembic commands ###
