"""empty message

Revision ID: 69f006805ce7
Revises:
Create Date: 2022-10-25 15:27:34.161543

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "69f006805ce7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_health",
        sa.Column("character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=True),
        sa.Column("total_hp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core.character.id"],
            name=op.f("fk_character_health_character_id_character"),
        ),
        sa.PrimaryKeyConstraint("character_id", name=op.f("pk_character_health")),
        schema="plugin_health",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_health", schema="plugin_health")
    # ### end Alembic commands ###
