"""empty message

Revision ID: bdc6d697a40f
Create Date: 2022-11-14 11:05:39.012234

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision = "bdc6d697a40f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(max_length=1137),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player")),
        schema="core",
    )
    op.create_table(
        "character",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_color", sa.String(), nullable=True),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["core.player.id"],
            name=op.f("fk_character_player_id_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character")),
        schema="core",
    )
    op.create_table(
        "player_window",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("top", sa.Integer(), nullable=False),
        sa.Column("left", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("component", sa.String(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core.character.id"],
            name=op.f("fk_player_window_character_id_character"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["core.player.id"],
            name=op.f("fk_player_window_player_id_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_window")),
        schema="core",
    )
    op.create_table(
        "player_window_setting",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("window_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["window_id"],
            ["core.player_window.id"],
            name=op.f("fk_player_window_setting_window_id_player_window"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_window_setting")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_window_setting", schema="core")
    op.drop_table("player_window", schema="core")
    op.drop_table("character", schema="core")
    op.drop_table("player", schema="core")
    # ### end Alembic commands ###
