"""empty message

Revision ID: 64fdec93ba19
Revises: 
Create Date: 2022-10-27 15:48:32.237035

"""
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "64fdec93ba19"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel")),
        schema="plugin_channels",
    )
    op.create_table(
        "channel_character",
        sa.Column("channel_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("character_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["plugin_channels.channel.id"],
            name=op.f("fk_channel_character_channel_id_channel"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core.character.id"],
            name=op.f("fk_channel_character_character_id_character"),
        ),
        sa.PrimaryKeyConstraint(
            "channel_id", "character_id", name=op.f("pk_channel_character")
        ),
        schema="plugin_channels",
    )
    op.create_table(
        "channel_message",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("character_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("channel_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("system", sa.Boolean(), nullable=True),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["plugin_channels.channel.id"],
            name=op.f("fk_channel_message_channel_id_channel"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core.character.id"],
            name=op.f("fk_channel_message_character_id_character"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_message")),
        schema="plugin_channels",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("channel_message", schema="plugin_channels")
    op.drop_table("channel_character", schema="plugin_channels")
    op.drop_table("channel", schema="plugin_channels")
    # ### end Alembic commands ###
