version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.10"
        # Optional Node.js version to install
        NODE_VERSION: "none"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=http"
      - "traefik.http.routers.backend.middlewares=stripapi@docker"
      - "traefik.http.middlewares.stripapi.stripprefix.prefixes=/api"

    volumes:
      - ..:/workspace:cached
      - nu-backend-vscode:/home/vscode/.vscode-server/extensions
      # And/or for VS Code Insiders
      - nu-backend-vscode-insiders:/home/vscode/.vscode-server-insiders/extensions
      - /var/run/docker.sock:/var/run/docker-host.sock

    ports:
      - "7000:7000"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - nu
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    env_file:
      - ../.env
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d
    env_file:
      - ../.env
    networks:
      - nu
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  traefik:
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - nu

volumes:
  postgres-data: null
  nu-backend-vscode: null
  nu-backend-vscode-insiders: null

networks:
  nu:
    name: nu
